add many features

diff --git a/bin/mysetup b/bin/mysetup
--- a/bin/mysetup
+++ b/bin/mysetup
@@ -1,21 +1,84 @@
 #!/bin/sh
 
 VERSION="0.0.1"
+target=$HOME/.mysetup
 
 usage() {
   echo "usage: $0 <command> [<args>]\n"
   echo "Available commands:"
+  echo "   tap         Tap config repository"
+  echo "   untap       Remove config repo"
+  echo "   bootstrap   Run bootstrap"
   echo "   version     Show version"
+}
+
+check_git() {
+  # check if git installed
+  git --version >& /dev/null
+  if [ $? != 0 ]; then
+    echo "Git not installed."
+    exit 10
+  fi
+}
+
+check_tap() {
+  if [ -d $target/repo ]; then
+    tapped=true
+  fi
 }
 
 cmd_version() {
   echo $VERSION
+  exit 0
+}
+
+cmd_untap() {
+  check_tap
+  if [ -z $tapped ]; then
+    echo "error: not tapped"
+    exit 1
+  fi
+  rm -rf $target/repo
+}
+
+cmd_bootstrap() {
+  check_tap
+  if [ -z $tapped ]; then
+    echo "error: not tapped, please run 'mysetup tap <url>'"
+    exit 1
+  fi
+
+  sh $target/repo/bootstrap.sh
+}
+
+cmd_tap() {
+  check_tap
+  if [ $tapped ]; then
+    echo "error: currently tapped"
+    exit 1
+  fi
+
+  check_git
+  if [ -z $cmd_arg ]; then
+    echo "error: specify repository, eq. 'mysetup tap <url>'"
+    exit 1
+  fi
+  echo "Tapping repo: $cmd_arg"
+
+  # cloning repo
+  git clone $cmd_arg $target/repo
+
+  if [ $? != 0 ]; then
+    echo "error: failed to clone repo"
+  fi
 }
 
 while getopts v opt; do
   case $opt in
     v) verbose=true
-       echo "Running in verbose mode."
+       echo "Running in verbose mode.";;
+
+    *) echo "unknown argument: $opt";;
   esac;
 done
 
@@ -25,9 +88,17 @@ if [ ! $1 ]; then
   exit 1
 fi
 
+cmd_arg=$2
+
 case $1 in
+  tap)
+    cmd_tap;;
+  untap)
+    cmd_untap;;
   version)
     cmd_version;;
+  bootstrap)
+    cmd_bootstrap;;
   *)
     echo "bad command: $1"
     usage
